### PR TITLE
MMF and FFM in work place and date spots

### PR DESCRIPTION
**Pull request by hawkeye-e**
- Add MMF option regardless of job in work place scene.
- Add MMF and FFM options regardless of job in date spot scene.
- Fix a bug that in date spot scene, if the name of the character contains certain Japanese hiragana or kanji, the speak with command is not set to disabled properly.

### CODE REVIEW

**Comment by bogus-things** [comment]
sorry for the delay -- this is some awesome stuff!

how do you feel about splitting out all the FFM/MMF stuff into a new folder with its own hooks & patches file? it seems like there's enough code here now for it to have its own space

**Comment by hawkeye-e** [comment]
yes, it should be nice. 
i will rearrange the file structure when i have time

**Comment by hawkeye-e** [comment]
Reorganize done!

**Review by bogus-things — APPROVED** [review]

**Comment by bogus-things** [comment]
Thanks for working on this stuff!

**Pull request merged**
